# Generated by Django 3.1.1 on 2020-11-24 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='connection.user')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nb_games', models.IntegerField()),
                ('epsilon', models.FloatField()),
            ],
            bases=('connection.user',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=146)),
                ('grid_point_db', models.CharField(max_length=146)),
                ('position', models.CharField(max_length=2)),
                ('q_table', models.FloatField()),
                ('ai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI.ai')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
