# Generated by Django 3.1.1 on 2020-11-24 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_State',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_player', models.IntegerField()),
                ('board', models.CharField(max_length=146)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Player',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.CharField(max_length=5)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game_state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.user')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
