# Generated by Django 3.1.1 on 2020-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_player',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
