# Generated by Django 3.1.1 on 2020-10-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('color1', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('G', 'Green')], max_length=1)),
                ('color2', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('G', 'Green')], max_length=1)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.user_data')),
            ],
        ),
    ]
